### ISSUE TITLE
Кхэм, ты разобрался в этом сервере? У меня получилось запустить, но во время авторизации в игре возникает ошибка.

### ISSUE THREAD

**Issue by nVoxel** [DeadZoneLuna/WarTLS-3.6#2]
Кинь, пожалуйста, свою почту/ВК, если можешь.

**Comment by SheoSeptim** [comment]
well for me, it just throws socket errors while i'm trying to log-in.
https://i.imgur.com/V54mRe4.jpg

i have spent like 3-4 days fixing this and still same shit! have no fooking clue why it is not working.
BUT! if you run dedicated, ìt will log-in on wartls without any problem... (wth?!)
https://i.imgur.com/lRkmW3Q.jpg
i guess its just broken af(or not xd)
 
it would be nice if @DeadZoneLuna  help us and make a tutorial how to properly run this thing
i can even share with you(@DeadZoneLuna ) how to easily run a leaked 2011 client!
https://i.imgur.com/8jh9y3F.jpg
https://i.imgur.com/ZOSK3XN.jpg
(guess not many people managed this shit to work. :) )

kind regards,
- sheo.

**Comment by nVoxel** [comment]
> well for me, it just throws socket errors while i'm trying to log-in.
> https://i.imgur.com/V54mRe4.jpg
> 
> i have spent like 3-4 days fixing this and still same shit! have no fooking clue why it is not working.
> BUT! if you run dedicated, ìt will log-in on wartls without any problem... (wth?!)
> https://i.imgur.com/lRkmW3Q.jpg
> i guess its just broken af(or not xd)
> 
> it would be nice if @DeadZoneLuna help us and make a tutorial how to properly run this thing
> i can even share with you(@DeadZoneLuna ) how to easily run a leaked 2011 client!
> https://i.imgur.com/ni4Dr83.jpg
> https://i.imgur.com/ZOSK3XN.jpg
> (guess not many people managed this shit to work. :) )
> 
> kind regards,
> 
> * sheo.

I even don't understand where does this emulator keep passwords, so I get stuck in in-game authorization.
Do you use openfire or xampp+prosody+redis? I use Microsoft SQL Server and maybe emulator can't normally work with it.
This is leaked emulator and as far as I know ProjectX and BlackSun (private servers like ARX) use updated version of this one, but I hope he actually help us.
Btw I guess our Russian comrades already know how to run wf2011.

**Comment by SheoSeptim** [comment]
sorry for late reply! i haven't had access to the Internet for 3 days haha
cant say anything about openfire because i didn't use it since 2016
but prosody and redis is definitely will not work(already tested this).
and yes i have using MS SQL too

>I even don't understand where does this emulator keep passwords, so I get stuck in in-game authorization.

after couple tests and looking in code, i might say, that  this emulator is not really "fully" leaked at all. it is cut and broken.
no matter what login or password you'll use, nothing will change. 
the point is, it is not even use rows from sql
it just connects to your database and do nothing. that's the reason why we can't pass auth state.

> This is leaked emulator and as far as I know ProjectX and BlackSun (private servers like ARX) use updated version of this one, but I hope he actually help us.

from what i know, arx didn't use emulators and all that stuff
they had leaked VN dev build that was avaliable on official site for some time but was removed very fast.
btw did they got sued? all their sites is dead for a loooong time :(  

> Btw I guess our Russian comrades already know how to run wf2011.

yeah ì see. really hope that someone releases emulator for old clients like 2011 & 2012
i need it so bad D:

**Comment by nVoxel** [comment]
> after couple tests and looking in code, i might say, that this emulator is not really "fully" leaked at all. it is cut and broken.

Well, I found one man who maybe have a newer version of this emulator (if I get it I can share it with u). Otherwise I'll try to fix it later.

> yeah ì see. really hope that someone releases emulator for old clients like 2011 & 2012

 Also he said he will make video tutorial about 2011 server.

**Comment by SheoSeptim** [comment]
> > after couple tests and looking in code, i might say, that this emulator is not really "fully" leaked at all. it is cut and broken.
> 
> Well, I found one man who maybe have a newer version of this emulator (if I get it I can share it with u). Otherwise I'll try to fix it later.
> 
> > from what i know, arx didn't use emulators and all that stuff
> > they had leaked VN dev build that was avaliable on official site for some time but was removed very fast.
> 
> Yeah, I know. It was an example, because you maybe don't know these servers.
> 
> > yeah ì see. really hope that someone releases emulator for old clients like 2011 & 2012
> 
> Also he said he will make video tutorial about 2011 server.

oof guess i'm late :( (hope not)

you actually the first one who trying to help me
for all those bloody years no one helped me. no one.
i was just being ignored. 
e.g, when some people  found a way how to spawn with inventory on in-game maps, i tried to do the same thing. i  just didn't know how to properly set up this query(software i used just didn't parse this query for some reason. i also knew it can be done with ItemSystem.GiveItem but i skipped that)
i asked them for help, but no one responded. they just ignored me.
then i've just gave up on these things.

but finally, after a year i found somewhere a new version of emulator i did use(rubens 4.0 emulator)
and then i made my first map! https://imgur.com/I4tTMY8
i was so glad that inventory and other stuff really works :p
sad thing was pve. it had no ai's. my goal always was pve. i want to make a mission with cutscenes. just for test
but there is no point making them on 2014-2017 clients

and now, knowing that 2011 client has ai's, i really want to experiment with pve stuff... but i don't have a working emulator for it

if you have one and can share, pm me on discord AnviFTW #6095
you will make me a happiest man in the world(yes i am idiot hahah)


thanks :)

**Comment by SheoSeptim** [comment]
> > after couple tests and looking in code, i might say, that this emulator is not really "fully" leaked at all. it is cut and broken.
> 
> Well, I found one man who maybe have a newer version of this emulator (if I get it I can share it with u). Otherwise I'll try to fix it later.
> 
> > from what i know, arx didn't use emulators and all that stuff
> > they had leaked VN dev build that was avaliable on official site for some time but was removed very fast.
> 
> Yeah, I know. It was an example, because you maybe don't know these servers.
> 
> > yeah ì see. really hope that someone releases emulator for old clients like 2011 & 2012
> 
> Also he said he will make video tutorial about 2011 server.

yep i'm too late :(
but anyway if you are still here
i can make a private tutorial for you: how to add working AI's on your map (only 2011 client. demonstration: https://youtu.be/BPPrVZEiTw8).
i really need emulator for this client
please D:

**Comment by nVoxel** [comment]
Why late? Check discord.

**Comment by moeray** [comment]
Do you guys knows anything about this project? can it make pvp and pve available?

**Comment by moeray** [comment]
> sorry for late reply! i haven't had access to the Internet for 3 days haha
> cant say anything about openfire because i didn't use it since 2016
> but prosody and redis is definitely will not work(already tested this).
> and yes i have using MS SQL too
> 
> > I even don't understand where does this emulator keep passwords, so I get stuck in in-game authorization.
> 
> after couple tests and looking in code, i might say, that this emulator is not really "fully" leaked at all. it is cut and broken.
> no matter what login or password you'll use, nothing will change.
> the point is, it is not even use rows from sql
> it just connects to your database and do nothing. that's the reason why we can't pass auth state.
> 
> > This is leaked emulator and as far as I know ProjectX and BlackSun (private servers like ARX) use updated version of this one, but I hope he actually help us.
> 
> from what i know, arx didn't use emulators and all that stuff
> they had leaked VN dev build that was avaliable on official site for some time but was removed very fast.
> btw did they got sued? all their sites is dead for a loooong time :(
> 
> > Btw I guess our Russian comrades already know how to run wf2011.
> 
> yeah ì see. really hope that someone releases emulator for old clients like 2011 & 2012
> i need it so bad D:

In fact, ARX may not be using leaked VN dev build. As I Know, they can always update their server version in time, so maybe they have friends inside Vietnamese WF agents. 
Besides, ARX also sold their server files, the price is about 8k dollars. Really hope to have a rich and kind person to buy one and share it.
